### ISSUE TITLE
"500 Internal Server Error" on certain TV show

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#18]
Hi

I'm using the latest git version on Mac OS X 10.8.2.

I have a bunch of recently added TV Shows that gives me this error when I click on them (older shows work fine):

PS. Nyaran: It has happened before, and you replied that they had become corrupted in my DB and I had to remove them, and re-add, but it was after you fixed something first - any ideas how to fix/avoid this?

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2690, in displayShow
    return _munge(t)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 125, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_Applications_Sick_Beard_gui_slick_interfaces_default_displayShow_tmpl.py", line 467, in respond
ValueError: invalid literal for int() with base 10: 'en'

**Comment by Nyaran** [comment]
When I back to home (i'm at work now) I try to fix it

**Comment by MartinAyla** [comment]
Thanks for the quick reply.

Here are some of names:

"Destination Truth"

"My Ghost Story: Caught on Camera"

"Paranormal State"

**Comment by isetz** [comment]
Ok, it seems that Nyaran knows where to fix so we'll see, later :P
