### ISSUE TITLE
Encoding issues

### ISSUE THREAD

**Issue by isetz** [Pistachitos/Sick-Beard#20]
Sometimes thetvdb puts typographic quotes that cause SickBeard crashes due to encoding problems when looking for subs. If we fix the episode name then there's no problem. But today I came across this crash... and the word is "Déjà" and still it's causing problems... we have to find a fix for this encoding issues.

<pre>
Mar-15 04:27:37 DEBUG    SHOWQUEUE-REFRESH :: 255316: Creating episode from /volume1/Downloads/Series/Elementary/Elementary - 1x18 - DÃ©jÃ  Vu All Over Again.mkv
Mar-15 04:27:37 DEBUG    SHOWQUEUE-REFRESH :: 255316: Creating episode object from /volume1/Downloads/Series/Elementary/Elementary - 1x18 - DÃ©jÃ  Vu All Over Again.mkv
Mar-15 04:27:37 DEBUG    SHOWQUEUE-REFRESH :: 255316: /volume1/Downloads/Series/Elementary/Elementary - 1x18 - DÃ©jÃ  Vu All Over Again.mkv parsed to Elementary 1x18
Mar-15 04:27:37 DEBUG    SHOWQUEUE-REFRESH :: Setter sets location to /volume1/Downloads/Series/Elementary/Elementary - 1x18 - DÃ©jÃ  Vu All Over Again.mkv
Mar-15 04:27:37 DEBUG    SHOWQUEUE-REFRESH :: 255316: Not saving episode to db - record is not dirty
Mar-15 04:27:38 ERROR    SHOWQUEUE-REFRESH :: 255316: Could not refresh subtitles
Mar-15 04:27:38 DEBUG    SHOWQUEUE-REFRESH :: Traceback (most recent call last):
  File "/volume1/@appstore/sickbeard/share/SickBeard/sickbeard/tv.py", line 285, in loadEpisodesFromDir
    curEpisode.refreshSubtitles()
  File "/volume1/@appstore/sickbeard/share/SickBeard/sickbeard/tv.py", line 1159, in refreshSubtitles
    self.subtitles = subtitles.subtitlesLanguages(self.location)
  File "/volume1/@appstore/sickbeard/share/SickBeard/sickbeard/subtitles.py", line 69, in subtitlesLanguages
    video = subliminal.videos.Video.from_path(video_path)
  File "/volume1/@appstore/sickbeard/share/SickBeard/lib/subliminal/videos.py", line 81, in from_path
    result = Episode(path, guess['series'], guess['season'], guess['episodeNumber'], title, guess)
  File "/volume1/@appstore/sickbeard/share/SickBeard/lib/subliminal/videos.py", line 183, in __init__
    super(Episode, self).__init__(path, guess, imdbid)
  File "/volume1/@appstore/sickbeard/share/SickBeard/lib/subliminal/videos.py", line 61, in __init__
    if os.path.exists(path):
  File "/opt/lib/python2.6/genericpath.py", line 18, in exists
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 58: ordinal not in range(128)</pre>

**Comment by lune001** [comment]
I've got the same issue here
