### ISSUE TITLE
Error when auto-processing

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#22]
From time to time, I can see that Sick-Beard has stopped auto-processing my downloads.

Usually, if I try and manually post-process the downloads, it works.

If I check the Sabnzbd script log, I can see this error when it happens:

```
      Loading config from /Users/martin/Library/Application Support/SABnzbd/scripts/autoProcessTV.cfg
```

Opening URL: https://localhost:5001/home/postprocess/processEpisode?nzbName=Finding.Bigfoot.S03E19.Bigfoot.the.Friendly.Ghost.720p.HDTV.x264-DHD.nzb&quiet=1&dir=%2FVolumes%2FPromise%2FUsenet%2Fsickbeard%2FFinding.Bigfoot.S03E19.Bigfoot.the.Friendly.Ghost.720p.HDTV.x264-DHD
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"

"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head>

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>

<title>500 Internal Server Error</title>

<style type="text/css">

#powered_by {

    margin-top: 20px;

    border-top: 2px solid black;

    font-style: italic;

}



#traceback {

    color: red;

}

</style>
```

</head>

```
<body>

    <h2>500 Internal Server Error</h2>

    <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>

    <pre id="traceback">Traceback (most recent call last):
```

  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond

```
response.body = self.handler()
```

  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in **call**

```
self.body = self.oldhandler(*args, **kwargs)
```

  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__

```
return self.callable(*self.args, **self.kwargs)
```

  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 1961, in processEpisode

```
result = processTV.processDir(dir, nzbName)
```

  File "/Applications/Sick-Beard/sickbeard/processTV.py", line 108, in processDir

```
process_result = processor.process()
```

  File "/Applications/Sick-Beard/sickbeard/postProcessor.py", line 857, in process

```
cur_ep.downloadSubtitles()
```

  File "/Applications/Sick-Beard/sickbeard/tv.py", line 1179, in downloadSubtitles

```
self.subtitles_searchcount = self.subtitles_searchcount + 1
```

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

</pre>

```
<div id="powered_by">

<span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.0rc1</a></span>

</div>

</body>
```

</html>

**Comment by MartinAyla** [comment]
sorry about the formatting, don't know how to fix it!

**Comment by MartinAyla** [comment]
I just tried to manually post-process and I got this error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 1961, in processEpisode
    result = processTV.processDir(dir, nzbName)
  File "/Applications/Sick-Beard/sickbeard/processTV.py", line 108, in processDir
    process_result = processor.process()
  File "/Applications/Sick-Beard/sickbeard/postProcessor.py", line 857, in process
    cur_ep.downloadSubtitles()
  File "/Applications/Sick-Beard/sickbeard/tv.py", line 1179, in downloadSubtitles
    self.subtitles_searchcount = self.subtitles_searchcount + 1
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

**Comment by MartinAyla** [comment]
Update:

I disabled subtitles for the show and then the manual post-processing worked…

Any ideas how to fix it so I don't have to disable subs for the shows?

Thanks

**Comment by isetz** [comment]
Can you please check if this still happens using the last updated version of SB??

**Comment by Nyaran** [comment]
No report in two months
