### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#42]
I'm getting this error today, using latest github code.

I happens when it tries to post-process:

```
       Loading config from /Users/martin/Library/Application Support/SABnzbd/scripts/autoProcessTV.cfg
```

Opening URL: https://localhost:5001/home/postprocess/processEpisode?nzbName=The.Daily.Show.2013.07.22.Louis.CK.720p.HDTV.x264-2HD.nzb&quiet=1&dir=%2FVolumes%2FPromise%2FUsenet%2Fsickbeard%2FThe.Daily.Show.2013.07.22.Louis.CK.720p.HDTV.x264-2HD
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"

"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">

<html>

<head>

```
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>

<title>500 Internal Server Error</title>

<style type="text/css">

#powered_by {

    margin-top: 20px;

    border-top: 2px solid black;

    font-style: italic;

}



#traceback {

    color: red;

}

</style>
```

</head>

```
<body>

    <h2>500 Internal Server Error</h2>

    <p>The server encountered an unexpected condition which prevented it from fulfilling the request.</p>

    <pre id="traceback">Traceback (most recent call last):
```

  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond

```
response.body = self.handler()
```

  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in **call**

```
self.body = self.oldhandler(*args, **kwargs)
```

  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__

```
return self.callable(*self.args, **self.kwargs)
```

  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2096, in processEpisode

```
result = processTV.processDir(dir, nzbName)
```

  File "/Applications/Sick-Beard/sickbeard/processTV.py", line 108, in processDir

```
process_result = processor.process()
```

  File "/Applications/Sick-Beard/sickbeard/postProcessor.py", line 890, in process

```
proper_path = ep_obj.proper_path()
```

  File "/Applications/Sick-Beard/sickbeard/tv.py", line 2016, in proper_path

```
result = self.formatted_filename()
```

  File "/Applications/Sick-Beard/sickbeard/tv.py", line 2077, in formatted_filename

```
return ' '.join(self._format_pattern(name_groups[-1], multi).split())
```

  File "/Applications/Sick-Beard/sickbeard/tv.py", line 1901, in _format_pattern

```
replace_map = self._replace_map()
```

  File "/Applications/Sick-Beard/sickbeard/tv.py", line 1861, in _replace_map

```
'%0AE': '%03d' % self.absolute_number,
```

TypeError: %d format: a number is required, not NoneType

</pre>

```
<div id="powered_by">

<span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.0rc1</a></span>

</div>

</body>
```

</html>

**Comment by Nyaran** [comment]
Something about absolute numbering support, I will try to check it

**Comment by MartinAyla** [comment]
I still get this error, both with the Daily Show and Project Catwalk (only with some episodes though):

> Traceback (most recent call last):
>   File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
>     response.body = self.handler()
>   File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
>     self.body = self.oldhandler(_args, *_kwargs)
>   File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
>     return self.callable(_self.args, *_self.kwargs)
>   File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2096, in processEpisode
>     result = processTV.processDir(dir, nzbName)
>   File "/Applications/Sick-Beard/sickbeard/processTV.py", line 108, in processDir
>     process_result = processor.process()
>   File "/Applications/Sick-Beard/sickbeard/postProcessor.py", line 890, in process
>     proper_path = ep_obj.proper_path()
>   File "/Applications/Sick-Beard/sickbeard/tv.py", line 2016, in proper_path
>     result = self.formatted_filename()
>   File "/Applications/Sick-Beard/sickbeard/tv.py", line 2077, in formatted_filename
>     return ' '.join(self._format_pattern(name_groups[-1], multi).split())
>   File "/Applications/Sick-Beard/sickbeard/tv.py", line 1901, in _format_pattern
>     replace_map = self._replace_map()
>   File "/Applications/Sick-Beard/sickbeard/tv.py", line 1861, in _replace_map
>     '%0AE': '%03d' % self.absolute_number,
> TypeError: %d format: a number is required, not NoneType
