### ISSUE TITLE
Web UI doesn't work (after update today)

### ISSUE THREAD

**Issue by MartinAyla** [Pistachitos/Sick-Beard#8]
Hi
## I updated to the latest version an hour ago, and now the web UI shows this error when Sick-Beard starts:

_Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2356, in index
    t = PageTemplate(file="home.tmpl")
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 70, in **init**
    super(PageTemplate, self).**init**(_args, **KWs)
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1259, in **init**
    self._compile(source, file, compilerSettings=compilerSettings)
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1553, in _compile
    keepRefToGeneratedCode=True)
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 740, in compile
    settings=(compilerSettings or {}))
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Compiler.py", line 1575, in __init__
    source = unicode(source)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
## UnicodeDecodeError: 'utf8' codec can't decode byte 0xb7 in position 3123: invalid start byte*

Any ideas?

**Comment by isetz** [comment]
Just noticed about the same issue here. Nyaran's going to push a fix right now :)

**Comment by MartinAyla** [comment]
Great :)

And thanks for the quick reply!

**Comment by Nyaran** [comment]
Push done, update your local
http://localhost:8081/manage/manageSearches/forceVersionCheck or download again (don't forget backup config.ini and sickbeard.db)

**Comment by MartinAyla** [comment]
Thanks a lot I killed the python process, did a "git pull", started it again, and now the web UI works again :)

Thanks very much for the fast replies!

**Comment by MartinAyla** [comment]
Sorry, just found out that when I click certain shows in the web UI, I get a new error:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2696, in displayShow
    return _munge(t)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 125, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_Applications_Sick_Beard_gui_slick_interfaces_default_displayShow_tmpl.py", line 432, in respond
ValueError: invalid literal for int() with base 10: 'en'

**Comment by Nyaran** [comment]
What branch are you using? Pistachitos or Anime-dev?

Pd. Next time open a new issue please

**Comment by MartinAyla** [comment]
Pistachitos

(OK, didn't know if it was a new issue)

**Comment by Nyaran** [comment]
I don't have idea what is throwing that error :s
With which shows appears that error?

**Comment by MartinAyla** [comment]
I thought it only happened with shows with special characters in the name, because it happens with:

National Geographic: UFO Europe Untold Stories

Oliver Stone's Untold History of the United States

Fact or Faked: Paranormal Files

But it also happens with:

Finding Bigfoot

Ancient Aliens

The Daily Show with Jon Stewart

## This is the error for The Daily Show (it looks different than the other error I think):

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2696, in displayShow
    return _munge(t)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 125, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_Applications_Sick_Beard_gui_slick_interfaces_default_displayShow_tmpl.py", line 722, in respond

## NotFound: cannot find 'split' while searching for 'split'

I hope you can find out what's wrong!

Thanks again
Martin

**Comment by Nyaran** [comment]
I can't reproduce your problem
Send me your sickbeard.db and config.ini, please (upload to mediafire)

**Comment by MartinAyla** [comment]
OK, thanks for the help, here they are:

http://ge.tt/9B6gUmT?c

Ps. It stopped working recently, within the last week or so (I can access the shows with the iPhone app Qouch, which uses the API, so it must we related to the web UI).

Regards
Martin

**Comment by MartinAyla** [comment]
I just did a "git pull" and now I can't see the web UI at all, I get this error in the Safari browser:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2358, in index
    return _munge(t)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 125, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_Applications_Sick_Beard_gui_slick_interfaces_default_home_tmpl.py", line 405, in respond
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

/Martin

**Comment by Nyaran** [comment]
I know that bug, just wait for fix ;)

**Comment by Nyaran** [comment]
Last reported bug fixed ;)

**Comment by MartinAyla** [comment]
Yes, it works again now :)

The same shows as before still don't work though (as to be expected).

**Comment by Nyaran** [comment]
Oliver Stone's Untold History of the United States
National Geographic: UFO Europe Untold Stories
How I Met Your Mother
Finding Bigfoot
Fact or Faked: Paranormal Files

That shows are corruped on your DB, remove it from your SB and readd (you can do it on Mass Update page)

**Comment by MartinAyla** [comment]
Thanks Nyaran!

Can I remove them, and re-add without loosing my settings (which episodes are downloaded, which are not)?

Or do I have to start completely new/fresh with those shows?

**Comment by Nyaran** [comment]
Remove they from SB, and to readd use "Add existing show", then it scan the folder automatically to mark what episodes was downloaded

**Comment by MartinAyla** [comment]
I get an error if I click on "The Daily Show" too, does that mean it's corrupted too?

Should I delete and re-add all the shows that give the "Internal 500" error in the web UI?

Thanks

**Comment by Nyaran** [comment]
At the end of error page says " ValueError: invalid literal for int() with base 10: 'en'"???
If is different post it

Nervermind, I forgot that I have your DB xD.
That is different error, don't delete

**Comment by MartinAyla** [comment]
This is for The Daily Show:

500 Internal Server Error

The server encountered an unexpected condition which prevented it from fulfilling the request.

Traceback (most recent call last):
  File "/Applications/Sick-Beard/cherrypy/_cprequest.py", line 660, in respond
    response.body = self.handler()
  File "/Applications/Sick-Beard/cherrypy/lib/encoding.py", line 193, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/Applications/Sick-Beard/cherrypy/_cpdispatch.py", line 25, in __call__
    return self.callable(_self.args, *_self.kwargs)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 2696, in displayShow
    return _munge(t)
  File "/Applications/Sick-Beard/sickbeard/webserve.py", line 125, in _munge
    return unicode(string).encode('utf-8', 'xmlcharrefreplace')
  File "/Library/Python/2.7/site-packages/Cheetah-2.4.4-py2.7-macosx-10.8-intel.egg/Cheetah/Template.py", line 1010, in __unicode__
    return getattr(self, mainMethName)()
  File "_Applications_Sick_Beard_gui_slick_interfaces_default_displayShow_tmpl.py", line 722, in respond
NotFound: cannot find 'split' while searching for 'split'

**Comment by Nyaran** [comment]
Fixed, update your SB
